#########################################################################
###                                                                   ###
###              SOLO PARA USO EN SERVER DE PRODUCCION                ###
###                                                                   ###
###    TRAEFIK NO USA VOLUMES NI NAMED VOLUMES -  SOLO BIND MOUNT     ###
###                                                                   ###
#########################################################################
services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    hostname: traefik
    restart: unless-stopped
    depends_on:
      - dockersocket
    security_opt:
      - no-new-privileges:true
    networks:
      - inverseproxy_shared
      - public
      - private
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./acme.json:/acme.json
  dockersocket:
    image: tecnativa/docker-socket-proxy:0.2
    privileged: true
    networks:
      private:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      NETWORKS: 1
      SERVICES: 1
      SWARM: 1
      TASKS: 1
    restart: unless-stopped
networks:
  inverseproxy_shared:
    external: true
  private:
    internal: true
    driver_opts:
      encrypted: 1
  public:
